CREATE USER fin_app
    IDENTIFIED BY fin_app_pwd
    DEFAULT TABLESPACE ts_fin_data
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON ts_fin_data;

GRANT CREATE SESSION TO fin_app;
GRANT CREATE TABLE TO fin_app;
GRANT CREATE VIEW TO fin_app;
GRANT CREATE SEQUENCE TO fin_app;
GRANT CREATE PROCEDURE TO fin_app;
GRANT CREATE TRIGGER TO fin_app;
GRANT CREATE TYPE TO fin_app;
GRANT CREATE SYNONYM TO fin_app;
GRANT CREATE MATERIALIZED VIEW TO fin_app;


